### ISSUE TITLE
Project name sugestion(s)

### ISSUE THREAD

**Issue by mjarkk** [mjarkk/general_programming_language#11]
I think i have a nice project name.

**talpa**
[It's Latin for chameleon](https://translate.google.nl/#view=home&op=translate&sl=en&tl=la&text=chameleon)  
Just like a chameleon this code and change into various forms.  
A lot of names are derived from the Latin translation and the name is quite original and it's spelled the same as you speak it.  

If you @TheOtterlord also have suggestions feel free to suggest them so we can give this project a name :).

**Comment by theotterlord** [comment]
While I really like the name, after a [quick search](https://www.ecosia.org/search?q=talpa&addon=firefox&addonversion=4.0.4) I found quite a few things with the same name. Including the [Talpa Network](https://en.wikipedia.org/wiki/Talpa_Network). The open-source guide has a few [tools](https://opensource.guide/starting-a-project/#avoiding-name-conflicts) for name checking. I like the whole chameleon aspect and wish to explore more names around this. I'll have a look around :-)

**Comment by theotterlord** [comment]
Another name I considered was [Patria](https://translate.google.nl/#view=home&op=translate&sl=en&tl=la&text=native). Sadly, this has also been used a lot. I am starting to doubt we will find a truly unique name. Maybe we should just make sure that the name has not been used for a big project or registered company?

**Comment by theotterlord** [comment]
By the way, I think this would mean that talpa could be considered valid as there are no big projects on GitHub and the talpa network is unrelated and appends network. We could always call it talpa-lang if we need to, but I think that talpa would be fine. 

What do you think?

**Comment by mjarkk** [comment]
Hmmm i had not given talpa a search yet, a bit unfortunately there is already a big company using the name.  
Though i think the name is oke when adding lang to it as you said and beside that adding lang to the name will make it more searchable.  
If we where to use that i think it's best to mimic what golang did (`https://github.com/golang/go`) where they use golang as org name and go as repo name.  
i'm not sure if we should use the dash in between so rather use talpalang over talpa-lang  

The name patria sounds fine but it has been translated from something really generic so no wonder that a lot of things already use it and there might come more oss project with that name so maybe not use that.  

Oh i also thought that it would be cool to have a chameleon as mascot just like go did with the [gopher](https://blog.golang.org/gopher). People much faster remember something when it has a logo and if the logo is original.

**Comment by theotterlord** [comment]
talpalang works. I agree with using the golang/go markup. This is a really nice way to do it. 

I guessed we would have a chameleon mascot. I’ll draw some logo concepts later.

**Comment by mjarkk** [comment]
Great lets go with that name then :)  

Do you want to create the org, or shall i make it?  
I guess we should both be an admin and limit this repo it's master branch to be protected so everything needs to be dune via merge requests.

**Comment by theotterlord** [comment]
I think you should make it. I'm new to GitHub so bound to mess something up :-)

Yeah, using the pull requests helps keep everything organised, protected and tidy.

**Comment by theotterlord** [comment]
By the way, we need an extension that suits our new name. 
What do you think it should be?

**Comment by mjarkk** [comment]
Ah that's a good one, i think it should defensively reflect the name so i guess it's something in the realms of: 
- `.t` typing .t in vscode already shows a file icon so we can't really use this one i guess
- `.ta` should work but to me this one sounds a bit boring and not rememberable
- `.tal` kinda the same as `.ta` though this one is longer so more letters to remember but also more original than the above
- `.talp` nice one but to long to type out i think
- `.tp` ***T**al **P**a* A nice one though i directly start to think about teleportation :).
- `.tlp` this one sounds like `.tp` but more complicated so i don't think this is a good idea

What do you think?

**Comment by theotterlord** [comment]
Nice. 

I quite like `.tp` and `.tlp` as they seem to suit the language more. 
Out of the two of them, I'd say I prefer `.tp` as it is shorter although it is a close choice.

**Comment by mjarkk** [comment]
Lets go for the .**T**ele**P**ortation file extension then :)

**Comment by mjarkk** [comment]
@TheOtterlord iv'e created an org: https://github.com/orgs/talpalang  
I've send you an invite i think it should show up in your email somewhere

**Comment by mjarkk** [comment]
Another think, i've imported this project to [talpalang/talpa](https://github.com/talpalang/talpa) but this means you will have to run git clone again to work on the repo.  
if you just add the a new remote with git to your old project git will give a lot of errors, it's probebly fixable but i have never bothered doing so in any project it's easier to just do a git clone again.

**Comment by mjarkk** [comment]
So i have bought the domain name talpalang.org i guess we firstly just redirect it to the github org and later we could hosts some docs, info and a try it out compiler.

**Comment by theotterlord** [comment]
Great, I've joined and recloned the repository. I guess we can close this issue now :-)
